import { definitions } from "./data.js";

// the left hand side panel that contains the list of links to be clicked
const sectionLeft = document.querySelector(".section-left");

/** Render a DOM element with dynamic props generated by the values
 * in definitions
 */
function renderHTML(DOMElement, text, bulletPointText, image) {
  const HTMLText = `<p class='def-text'>${text}</p>`;
  const HTMLBulletPoints = `<div class="bullet-text">${bulletPointText}</div>`;
  const HTMLImage = image ? `<img class="image"src=${image}>` : null;

  DOMElement.innerHTML = image
    ? `${HTMLText}${HTMLBulletPoints}${HTMLImage}`
    : `${HTMLText}${HTMLBulletPoints}`;
}

function renderBulletPointsAsList(bulletPoints) {
  return bulletPoints
    .split(".")
    .slice(0, -1)
    .map((bulletPoint) => `<li class='list'>${bulletPoint}</li>`)
    .join("");
}

// When the user clicks on a link in the left panel update the DOM
sectionLeft.addEventListener("click", function (e) {
  const sectionRight = document.querySelector(".section-right");
  const selectedValue = e.target.id;
  const selectedDefinition = definitions.find(
    ({ title }) => title === selectedValue
  );

  const { image: imageUrl, text, bulletPointItems } = selectedDefinition;

  // When the user clicks on a list element set it's color to orange
  // and set the rest to black
  document.querySelectorAll(".section-left li").forEach((element) => {
    if (element.id === selectedValue) {
      element.style.color = "#F09E3F";
    } else {
      element.style.color = "black";
    }
  });

  renderHTML(
    sectionRight,
    text,
    renderBulletPointsAsList(bulletPointItems),
    imageUrl ?? null
  );
});
